source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-websocket'
gem 'alarm_decoder', git: 'git@github.com:jordanbyron/alarm_decoder.git'
# gem 'puma'
gem 'thin'
gem 'haml'
gem 'sass'
gem 'dotenv'
gem 'sinatra-contrib'
