source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-websocket'
gem 'alarm_decoder', git: 'git@github.com:jordanbyron/alarm_decoder.git'
gem 'thin'
gem 'haml'
gem 'sass'
gem 'dotenv'
gem 'garage_door', git: 'git@github.com:jordanbyron/garage_door.git'
